### ISSUE TITLE
Optional support for multiple workspaces for an entity

### ISSUE THREAD

**Issue by iiro** [globallogicuki/globallogic-backstage-plugins#51]
An entity can be spread into multiple states / workspaces; hence this would be important for some users if possible to implement.

**Comment by himeshladva** [comment]
@iiro Thanks! And welcome 👋🏽!

A couple of options come to mind.

### Option 1
We could change the annotation to be:
```yaml
annotations:
  - terraform/organization: 'org'
  - terraform/workspaces: 'workspace-1,workspace-2'
```

From memory, I don't think backstage lets you have a list as an annotation, so we'd have to go with a comma-separated list of workspace names.

We could then use the [List Runs in an Organization](https://developer.hashicorp.com/terraform/cloud-docs/api-docs/run#list-runs-in-an-organization) endpoint along with the `filter[workspace_names]` parameter to fetch the runs related to the given workspaces. Would need to verify whether this endpoint allows the `?include=created_by,plan` parameter. This endpoint should also allow us to efficiently fetch the latest run for the `TerraformLatestRun` card.

### Option 2
We could add a new annotation:
```yaml
annotations:
  - terraform/organization: 'org'
  - terraform/workspace: 'workspace-1'
  - terraform/additional-workspaces: 'workspace-2,workspace-3'
```

We would use the existing `terraform/workspace` for the `TerraformLatestRun` card.

We would use the above List Runs in an Organization endpoint, passing all workspaces from both annotations, for the main `TerraformRuns` component.

### Note
